"""Prepare and QC the native states for one scaffold. Upstream of everything else.

    X_D        DNA-compatible backbone (from the operator complex), no ligand
    X_I        induced backbone (from the effector complex), no ligand
    X_D_DNA    DNA-compatible backbone + operator
    X_I_DNA    induced backbone + operator      (built by superposition, see prepare())
    X_D_lig / X_I_lig   come from pose.py, which places the TARGET ligand

QC REJECTS; it does not warn. "Has a structure" is not "has a usable allosteric state":
  * is the bound heteroatom a real EFFECTOR or a crystallisation additive? A glycerol sitting in
    the pocket yields a confident, completely meaningless allosteric template.
  * is the DNA a real operator, or a short duplex / packing artefact?
  * is the oligomeric state right? TetR/LacI-family repressors work as DIMERS - with one chain the
    DBD-DBD geometry, i.e. the entire readout, is undefined.
  * does residue numbering match our reference? Constructs renumber silently.
  * are the design positions actually resolved, or are we inventing disordered density?

Worth checking rather than assuming: on TtgR, 2UXH/2UXO auth numbering happens to match UniProt
exactly (WT 11-mer HHAEMLLVNLH read from both), but that is luck, not a rule.
"""
import os
import csv
import json
import urllib.request
import numpy as np
from Bio.PDB import PDBParser, PDBIO, Select, Superimposer
from Bio.PDB.PDBExceptions import PDBConstructionWarning
import warnings
warnings.simplefilter("ignore", PDBConstructionWarning)

ADDITIVES = {"HOH", "SO4", "GOL", "EDO", "PO4", "CL", "NA", "K", "MG", "CA", "ZN", "MN", "ACT",
             "PEG", "PG4", "DMS", "TRS", "IOD", "BR", "NO3", "FMT", "EPE", "MPD", "BME", "CAC",
             "1PE", "P6G", "2PE", "PGE", "MRD", "IMD", "MES", "BEZ", "ACY", "EOH", "IPA",
             "UNL", "UNX", "HEZ", "HEX", "BU1", "DIO", "12P", "15P"}
DNA_RES = {"DA", "DT", "DG", "DC", "DU"}
MIN_OPERATOR_BP = 10


def fetch(pdb_id, out_dir):
    """ASYMMETRIC UNIT. Almost never what you want - see fetch_assembly()."""
    os.makedirs(out_dir, exist_ok=True)
    p = os.path.join(out_dir, "%s.pdb" % pdb_id.upper())
    if not os.path.exists(p):
        open(p, "wb").write(urllib.request.urlopen(
            "https://files.rcsb.org/download/%s.pdb" % pdb_id.upper(), timeout=60).read())
    return p


def fetch_assembly(pdb_id, out_dir, assembly=1):
    """BIOLOGICAL ASSEMBLY (.pdb1). This is what must be used, not the asymmetric unit.

    Verified the hard way on 1QPI (TetR-tetO, the ONLY TetR operator complex and therefore the
    foundation of the whole DNA-release criterion): its asymmetric unit contains ONE protein chain.
    The functional dimer is generated by crystallographic symmetry, so reading the ASU gives half a
    protein - and DBD-DBD geometry, hence Delta_d_DBD / Delta_theta_DBD / S_release, is undefined.
    Nothing would crash; we would simply compute confident nonsense from one DBD.

    The two representations differ per entry and both must be handled:
        1QPI  -> assembly is 2 MODEL blocks, symmetry copies, BOTH chains named 'A'
        1JT0  -> assembly is 1 MODEL block already containing chains A,B,C,D
    """
    os.makedirs(out_dir, exist_ok=True)
    p = os.path.join(out_dir, "%s_bio%d.pdb" % (pdb_id.upper(), assembly))
    if not os.path.exists(p):
        import gzip
        url = "https://files.rcsb.org/download/%s.pdb%d.gz" % (pdb_id.upper(), assembly)
        raw = gzip.decompress(urllib.request.urlopen(url, timeout=60).read())
        open(p, "wb").write(raw)
    return p


def _struct(pdb_path):
    return PDBParser(QUIET=True).get_structure("x", pdb_path)


def load_assembly(pdb_path):
    """-> a single Model with every symmetry copy merged and chains uniquely renamed.

    Multi-MODEL assemblies reuse chain IDs across copies, so a naive read collapses the dimer back
    to a monomer. Merging must happen before any chain counting or DBD geometry.
    """
    st = _struct(pdb_path)
    models = list(st)
    if len(models) == 1:
        return models[0]
    from Bio.PDB.Model import Model
    merged = Model(0)
    used = set()
    pool = [c for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"]
    for mi, m in enumerate(models):
        for ch in m:
            new_id = ch.id if (mi == 0 and ch.id not in used) else None
            if new_id is None:
                new_id = next((x for x in pool if x not in used), None)
                if new_id is None:
                    raise RuntimeError("ran out of chain IDs merging assembly")
            c = ch.copy()
            c.id = new_id
            c.detach_parent()
            merged.add(c)
            used.add(new_id)
    return merged


def classify_chains(model):
    prot, dna, het = [], [], []
    for ch in model:
        res = [r for r in ch if r.id[0] == " "]
        names = {r.get_resname().strip() for r in res}
        if res and names <= DNA_RES:
            dna.append(ch)
        elif len(res) > 30:
            prot.append(ch)
        for r in ch:
            if r.id[0] != " " and r.get_resname().strip() not in ADDITIVES:
                het.append((ch.id, r.get_resname().strip()))
    return prot, dna, het


def qc(pdb_path, expect_effector=None, expect_dimer=True, require_dna=False,
       design_positions=(), expect_wt_11mer=None):
    """-> (ok, report). Any problem is a rejection, not a warning."""
    rep = dict(pdb=os.path.basename(pdb_path), problems=[], notes=[])
    model = load_assembly(pdb_path)      # merged assembly: a multi-MODEL dimer must not
                                         # collapse to a monomer before chain counting
    prot, dna, het = classify_chains(model)
    rep["n_protein_chains"] = len(prot)
    rep["n_dna_chains"] = len(dna)
    rep["heteroatoms"] = sorted({h[1] for h in het})

    if expect_dimer and len(prot) < 2:
        rep["problems"].append(
            "only %d protein chain(s): this family works as a dimer, so DBD-DBD geometry - the "
            "whole readout - is undefined" % len(prot))

    if expect_effector:
        if not any(h[1].upper() == expect_effector.upper() for h in het):
            rep["problems"].append("effector %s absent (heteroatoms present: %s)"
                                   % (expect_effector, rep["heteroatoms"] or "none"))

    if require_dna:
        if not dna:
            rep["problems"].append("no DNA chain: operator release cannot be measured")
        else:
            bp = min(len([r for r in c if r.id[0] == " "]) for c in dna)
            rep["operator_bp"] = bp
            if bp < MIN_OPERATOR_BP:
                rep["problems"].append("duplex only %d bp - too short for a real operator, likely "
                                       "crystal packing" % bp)

    if design_positions:
        if not prot:
            rep["problems"].append("no protein chain to map design positions onto")
        else:
            ch = max(prot, key=lambda c: sum(1 for r in c if r.id[0] == " "))
            have = {r.id[1]: r.get_resname() for r in ch if r.id[0] == " "}
            # the mapping structure.run hands downstream: design position -> residue actually
            # deposited there. Without it run_stage sees residue_mapping=None and rejects the stage.
            rep["mapping"] = {int(p): have[p] for p in design_positions if p in have}
            missing = [p for p in design_positions if p not in have]
            if missing:
                rep["problems"].append("design positions unresolved: %s" % missing)
            elif expect_wt_11mer:
                from .physallo.aa_filter import one
                got = "".join(one(have[p]) for p in design_positions)
                rep["wt_mer_in_pdb"] = got
                if got != expect_wt_11mer:
                    rep["problems"].append(
                        "numbering mismatch: PDB gives %s, reference is %s - this construct "
                        "renumbers, map it explicitly" % (got, expect_wt_11mer))
                else:
                    rep["notes"].append("numbering matches reference (%s)" % got)
    return (not rep["problems"]), rep


class _Keep(Select):
    """Chain filter + heteroatom policy.

    KEPT RESIDUES ARE CHECKED BEFORE THE ADDITIVE LIST, not after. Several genuine cofactors are
    also common crystallisation additives - MG above all - so an additive-first test silently
    deletes the very thing that makes the effector an effector. For TetR the inducer is
    [Mg-tetracycline]+: Mg is coordinated by TAC O11/O12 and His100, and that coordination is what
    reaches alpha6. Dropping it turns DL/IL into "TAC alone", and a failed native control could
    then mean a broken six-state theory OR simply that we deleted the inducer.
    """

    def __init__(self, chains, drop_het=True, keep_resname=None, keep_cofactors=()):
        self.chains, self.drop_het = set(chains), drop_het
        keep = set()
        if keep_resname:
            keep.add(str(keep_resname).strip().upper())
        keep |= {str(c).strip().upper() for c in (keep_cofactors or ()) if c}
        self.keep = keep

    def accept_chain(self, c):
        return c.id in self.chains

    def accept_residue(self, r):
        if r.id[0] == " ":
            return True
        n = r.get_resname().strip().upper()
        if n in self.keep:            # explicit keeps win over the additive list
            return True
        if n in ADDITIVES:
            return False
        return not self.drop_het


def write_state(pdb_path, out_path, chains, drop_het=True, keep_ligand=None, keep_cofactors=()):
    io = PDBIO()
    io.set_structure(load_assembly(pdb_path))   # merged assembly, chains uniquely renamed
    io.save(out_path, _Keep(chains, drop_het, keep_ligand, keep_cofactors))
    return out_path


def transfer_ligand_complex(src_pdb, dst_pdb, resnames, pocket_resnums, out_path,
                            src_chain=None, dst_chain=None):
    """Move a LIGAND COMPLEX (effector + its cofactors) from one backbone to another as a RIGID
    BODY, by superposing the two pockets.

    For a metal-dependent effector the complex is the unit that matters: [Mg-tetracycline]+ is held
    together by Mg-O11/O12 coordination, so transferring the drug by MCS and leaving the metal
    behind - or re-placing it independently - destroys the geometry that actually triggers
    induction. Superposing on the POCKET (not the whole protein, not the DBD) and applying one
    transform to every atom of the complex keeps that coordination intact.

    -> (out_path, rms, n_pocket_atoms_used)
    """
    import copy
    from Bio.PDB.Structure import Structure
    from Bio.PDB.Model import Model

    keep = {str(r).strip().upper() for r in resnames}
    ms, md = load_assembly(src_pdb), load_assembly(dst_pdb)

    def _prot(model, want):
        prot = classify_chains(model)[0]
        if want:
            for c in prot:
                if c.id == want:
                    return c
        return max(prot, key=lambda c: sum(1 for r in c if r.id[0] == " "))

    cs, cd = _prot(ms, src_chain), _prot(md, dst_chain)
    want = set(int(p) for p in pocket_resnums)
    a = {r.id[1]: r["CA"] for r in cs if r.id[0] == " " and "CA" in r and r.id[1] in want}
    b = {r.id[1]: r["CA"] for r in cd if r.id[0] == " " and "CA" in r and r.id[1] in want}
    common = sorted(set(a) & set(b))
    if len(common) < 4:
        raise RuntimeError("only %d shared pocket CA between %s and %s - cannot transfer the "
                           "ligand complex reliably" % (len(common), os.path.basename(src_pdb),
                                                        os.path.basename(dst_pdb)))
    sup = Superimposer()
    sup.set_atoms([b[i] for i in common], [a[i] for i in common])

    complex_res = [r for ch in ms for r in ch
                   if r.get_resname().strip().upper() in keep]
    if not complex_res:
        raise RuntimeError("none of %s found in %s: nothing to transfer"
                           % (sorted(keep), os.path.basename(src_pdb)))
    sup.apply([atom for r in complex_res for atom in r])   # one transform for the whole complex

    merged = Structure("transferred")
    model = Model(0)
    merged.add(model)
    used = set()
    pool = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

    def _add(ch):
        c = copy.deepcopy(ch)
        cid = c.id if c.id not in used and str(c.id).strip() else next(
            x for x in pool if x not in used)
        c.id = cid
        used.add(cid)
        c.detach_parent()
        model.add(c)
        return c

    for ch in md:                       # destination backbone as-is
        _add(ch)
    from Bio.PDB.Chain import Chain     # the transferred complex goes in its own chain
    lig_chain = Chain(next(x for x in pool if x not in used))
    used.add(lig_chain.id)
    # a homodimer carries one copy of the complex per subunit, so the deposited residue ids repeat
    # (H_MG 223 twice). Renumber sequentially into the new chain rather than dropping a copy - both
    # subunits' effectors are real and the six states are scored on the dimer.
    for i, r in enumerate(complex_res, start=1):
        rc = copy.deepcopy(r)
        rc.detach_parent()
        het, _, icode = rc.id
        rc.id = (het, i, icode)
        lig_chain.add(rc)
    model.add(lig_chain)

    io = PDBIO()
    io.set_structure(merged)
    io.save(out_path)
    return out_path, float(sup.rms), len(common)


def verify_cofactors(pdb_path, cofactors, ligand_resname=None):
    """A required cofactor missing from a written state is a hard error, never a warning.

    -> counts per cofactor. Raises if any is absent: the whole point of declaring it required is
    that its absence changes what the six states mean.
    """
    if not cofactors:
        return {}
    model = load_assembly(pdb_path)
    found = {}
    for c in cofactors:
        name = str(c).strip().upper()
        found[name] = sum(1 for ch in model for r in ch
                          if r.get_resname().strip().upper() == name)
    missing = [k for k, v in found.items() if v == 0]
    if missing:
        raise RuntimeError(
            "required cofactor(s) %s absent from %s. For an effector that acts as a metal complex "
            "(e.g. [Mg-tetracycline]+) this state is not the effector state at all, and a native "
            "control built on it cannot be interpreted." % (missing, os.path.basename(pdb_path)))
    return found


def _core_ca(chain, exclude_range):
    """CA atoms of the ligand-binding core, i.e. everything OUTSIDE the DBD."""
    lo, hi = exclude_range
    return {r.id[1]: r["CA"] for r in chain
            if r.id[0] == " " and "CA" in r and not (lo <= r.id[1] <= hi)}


def build_induced_on_dna(holo_pdb, dna_pdb, out_path, dbd_range, chain_i=None, chain_d=None):
    """X_I_DNA: put the INDUCED conformation onto the operator complex.

    Superpose on the ligand-binding CORE only, never on the DBD: the DBD is the readout. Fitting
    the DBD would force the induced conformation onto the operator and erase exactly the clash we
    are trying to measure.

    The output MERGES the superposed induced protein (every subunit) with the operator DNA chains
    taken from the DNA complex. Re-saving the holo structure alone yields an "X_I_DNA" containing
    no DNA at all - state_builder then rejects the state, and the DNA-release term is unavailable.
    """
    import copy
    from Bio.PDB.Structure import Structure
    from Bio.PDB.Model import Model

    mi, md = load_assembly(holo_pdb), load_assembly(dna_pdb)
    pi = list(classify_chains(mi)[0])
    pd, dna_chains, _ = classify_chains(md)
    if not dna_chains:
        raise RuntimeError("%s carries no DNA chain: cannot build the operator-bound induced state"
                           % os.path.basename(dna_pdb))
    nres = lambda c: sum(1 for r in c if r.id[0] == " ")
    ci = mi[chain_i] if chain_i else max(pi, key=nres)
    cd = md[chain_d] if chain_d else max(pd, key=nres)

    a, b = _core_ca(ci, dbd_range), _core_ca(cd, dbd_range)
    common = sorted(set(a) & set(b))
    if len(common) < 40:
        raise RuntimeError("only %d shared core CA - cannot superpose reliably" % len(common))
    sup = Superimposer()
    sup.set_atoms([b[i] for i in common], [a[i] for i in common])
    # move the WHOLE induced protein, not only the reference chain: the other subunit belongs to
    # the same rigid body and would otherwise be left behind in the holo frame
    sup.apply([atom for ch in pi for r in ch for atom in r])

    merged = Structure("X_I_DNA")
    model = Model(0)
    merged.add(model)
    used = set()
    pool = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

    def _add(ch):
        c = copy.deepcopy(ch)          # deep-copied AFTER superposition, so it carries new coords
        cid = c.id
        if cid in used or not str(cid).strip():
            cid = next(x for x in pool if x not in used)
        c.id = cid
        used.add(cid)
        c.detach_parent()
        model.add(c)

    for ch in pi:
        _add(ch)
    for ch in dna_chains:              # the operator itself
        _add(ch)

    io = PDBIO()
    io.set_structure(merged)
    io.save(out_path)
    return out_path, float(sup.rms), len(common)


def prepare(tf_name, holo_pdb, dna_pdb, out_dir, design_positions, effector_resname,
            dbd_range, expect_wt_11mer=None):
    """-> {'X_D','X_I','X_D_DNA','X_I_DNA','qc'}; raises if QC rejects the scaffold."""
    os.makedirs(out_dir, exist_ok=True)
    report = {}
    ok_i, report["induced"] = qc(holo_pdb, expect_effector=effector_resname,
                                 design_positions=design_positions,
                                 expect_wt_11mer=expect_wt_11mer)
    ok_d, report["dna_bound"] = qc(dna_pdb, require_dna=True,
                                   design_positions=design_positions,
                                   expect_wt_11mer=expect_wt_11mer)
    if not (ok_i and ok_d):
        raise RuntimeError("QC rejected %s:\n%s" % (tf_name, json.dumps(report, indent=2)))

    mi, md = load_assembly(holo_pdb), load_assembly(dna_pdb)
    ci = [c.id for c in classify_chains(mi)[0]][:2]
    pd_, dna_, _ = classify_chains(md)
    cd_prot = [c.id for c in pd_][:2]
    out = {
        "X_I": write_state(holo_pdb, os.path.join(out_dir, "X_I.pdb"), ci),
        "X_D": write_state(dna_pdb, os.path.join(out_dir, "X_D.pdb"), cd_prot),
        "X_D_DNA": write_state(dna_pdb, os.path.join(out_dir, "X_D_DNA.pdb"),
                               cd_prot + [c.id for c in dna_]),
    }
    p, rms, n = build_induced_on_dna(holo_pdb, dna_pdb, os.path.join(out_dir, "X_I_DNA.pdb"),
                                     dbd_range)
    out["X_I_DNA"] = p
    report["superposition"] = dict(core_rms=rms, n_core_ca=n, note="fit on ligand-binding core "
                                   "only; DBD excluded because it is the readout")
    out["qc"] = report
    json.dump(report, open(os.path.join(out_dir, "structure_qc.json"), "w"), indent=2)
    return out


def resolution(pdb_id):
    """RCSB resolution, or None. Used only to order candidates - never to reject silently."""
    try:
        import urllib.request
        j = json.load(urllib.request.urlopen(
            "https://data.rcsb.org/rest/v1/core/entry/%s" % pdb_id, timeout=30))
        r = (j.get("rcsb_entry_info") or {}).get("resolution_combined")
        return float(r[0]) if r else None
    except Exception:
        return None


def pick_entries(row):
    """Choose the holo and DNA entries to build the two backbones from.

    Refuses the PurR trap: tier is computed from counts, and a TF whose every effector-bound
    structure is a TERNARY complex has n_ternary>0 but holo_pdbs empty. Such a scaffold still has
    a usable X_D (the ternary backbone) but its X_I is the apo state and its topology is inverted -
    that is a corepressor, and it must be routed as one rather than silently built backwards.
    """
    holo = [x for x in (row.get("holo_pdbs") or "").split(";") if x]
    dna = [x for x in (row.get("dna_pdbs") or "").split(";") if x]
    n_tern = int(row.get("n_ternary") or 0)
    notes = []
    if not holo and n_tern > 0:
        raise RuntimeError(
            "%s has no effector-only structure: all %d effector-bound entries are ternary "
            "(TF+DNA+ligand). Its tier=%s was computed by counting ternary as both holo and DNA. "
            "This is a corepressor topology - X_I is the APO state, not a holo one - and it must "
            "be declared as topology_mode: corepressor before it can be built."
            % (row["tf_name"], n_tern, row.get("tier")))
    if not holo:
        raise RuntimeError("%s: no holo structure, cannot define the induced backbone"
                           % row["tf_name"])
    if not dna:
        raise RuntimeError(
            "%s: no operator complex, so X_D is undefined and S_release cannot be measured. "
            "This is a Tier-2 scaffold (%s). Building X_D from a homology model is a separate "
            "decision, not a default." % (row["tf_name"], row.get("tier_note", "")))
    def best(ids):
        scored = [(resolution(i), i) for i in ids]
        known = sorted([t for t in scored if t[0] is not None])
        if known:
            return known[0][1], known[0][0]
        notes.append("no resolution metadata for %s; took the first entry" % ",".join(ids))
        return ids[0], None
    h, hr = best(holo)
    d, dr = best(dna)
    return {"holo": h, "holo_res": hr, "dna": d, "dna_res": dr,
            "holo_pool": holo, "dna_pool": dna, "notes": notes}


def load_row(tf_name, db_path=None):
    db_path = db_path or os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                                      "data", "atf_structure_db.csv")
    with open(db_path) as f:
        for r in csv.DictReader(f):
            if r["tf_name"] == tf_name:
                return r
    raise KeyError("%s not in %s" % (tf_name, db_path))


def resolve_design_positions(holo_pdb, ligand_resname, dbd_range=None, protected=(),
                             cutoff=5.0, out_json=None):
    """Read the design positions OFF THE STRUCTURE instead of trusting a hand-typed list.

    A user who downloads this should not have to know which residues line the pocket. The contact
    shell is measured from the deposited effector, then the readout domain (DBD) and any residues
    declared untouchable are removed - so the same command works on a scaffold nobody has curated.

    -> (positions, report). The report records what was found and what was excluded, and is written
    to out_json so a run can be audited later.
    """
    model = load_assembly(holo_pdb)
    lig = [a for ch in model for r in ch
           if r.id[0] != " " and r.get_resname().strip().upper() == ligand_resname.upper()
           for a in r if a.element != "H"]
    if not lig:
        raise RuntimeError("effector %s not found in %s: cannot resolve the pocket"
                           % (ligand_resname, os.path.basename(holo_pdb)))
    L = np.array([a.coord for a in lig])

    shell = set()
    for ch in classify_chains(model)[0]:
        for r in ch:
            if r.id[0] != " ":
                continue
            for a in r:
                if a.element == "H":
                    continue
                if np.linalg.norm(L - np.array(a.coord), axis=1).min() < cutoff:
                    shell.add(int(r.id[1]))
                    break

    excluded_dbd = set()
    if dbd_range:
        lo, hi = int(dbd_range[0]), int(dbd_range[1])
        excluded_dbd = {p for p in shell if lo <= p <= hi}     # the readout is never redesigned
    excluded_prot = {int(p) for p in (protected or ())} & shell
    positions = sorted(shell - excluded_dbd - excluded_prot)

    if not positions:
        raise RuntimeError("no designable pocket residue survived: shell=%d, DBD-excluded=%d, "
                           "protected-excluded=%d" % (len(shell), len(excluded_dbd),
                                                      len(excluded_prot)))
    report = {"source": os.path.basename(holo_pdb), "ligand": ligand_resname, "cutoff": cutoff,
              "contact_shell": sorted(shell), "excluded_dbd": sorted(excluded_dbd),
              "excluded_protected": sorted(excluded_prot), "design_positions": positions}
    if out_json:
        os.makedirs(os.path.dirname(os.path.abspath(out_json)), exist_ok=True)
        with open(out_json, "w") as f:
            json.dump(report, f, indent=2)
    return positions, report


def load_scaffold_meta(tf, path=None):
    """Per-scaffold parameters (effector residue, DBD boundary, pocket positions) from
    config/scaffolds.yaml.

    An unregistered scaffold is REFUSED rather than guessed. The structure database only knows
    which PDB entries exist; inventing a dbd_range would silently redefine the readout domain and
    inventing design_positions would redesign the wrong pocket - both while still producing
    confident numbers.
    """
    import yaml
    path = path or os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                                "config", "scaffolds.yaml")
    with open(path) as f:
        table = yaml.safe_load(f) or {}
    if tf not in table:
        raise RuntimeError(
            "scaffold '%s' has no entry in %s: effector_resname / dbd_range / design_positions "
            "cannot be derived from the structure database. Add them, checked against that "
            "scaffold's own structures, before designing on it. Registered: %s"
            % (tf, os.path.basename(path), ", ".join(sorted(table)) or "none"))
    return table[tf]


def run(ctx):
    """requires ctx['scaffold']; produces ctx['states'], ctx['residue_mapping']"""
    sc = ctx["scaffold"]
    tf = sc["tf_name"] if isinstance(sc, dict) else sc
    # route hands over a scaffold NAME; its parameters live in config/scaffolds.yaml. An explicit
    # dict from the caller overrides the table entry field by field.
    meta = dict(load_scaffold_meta(tf, ctx.get("scaffold_config")))
    if isinstance(sc, dict):
        meta.update({k: v for k, v in sc.items() if v is not None})

    row = load_row(tf, ctx.get("structure_db"))
    pick = pick_entries(row)
    # An explicitly declared pair OVERRIDES the resolution-based pick. Which entries constitute
    # this scaffold's native switch is a scientific choice, not a resolution contest: for TetR the
    # pair is 1QPI (WT + operator) and 2TRT (WT + TAC + Mg), while the higher-resolution 2TCT holds
    # 7-chlorotetracycline and would benchmark a different molecule.
    ref = meta.get("reference") or {}
    golden = meta.get("golden_pair") or {}
    forced_holo = golden.get("induced_state") or ref.get("holo")
    forced_dna = golden.get("dna_state") or ref.get("operator")
    if forced_holo:
        pick["holo"], pick["holo_forced"] = forced_holo, True
    if forced_dna:
        pick["dna"], pick["dna_forced"] = forced_dna, True

    out_dir = os.path.join(ctx["out_dir"], "states")
    holo = fetch_assembly(pick["holo"], out_dir)
    dna = fetch_assembly(pick["dna"], out_dir)

    # Design positions are RESOLVED FROM THE STRUCTURE by default. A hand-typed list in the config
    # is treated as an override and recorded as such - nobody downloading this should need to know
    # which residues line a pocket they have never seen.
    protected = [int(r) for r in (meta.get("protected_native_trigger") or [])]
    resolved, pocket_report = resolve_design_positions(
        holo, meta["effector_resname"], dbd_range=meta.get("dbd_range"), protected=protected,
        cutoff=float(meta.get("pocket_cutoff", 5.0)),
        out_json=os.path.join(ctx["out_dir"], "resolved_design_positions.json"))
    declared = [int(p) for p in (meta.get("design_positions") or ())]
    if declared:
        design_positions = declared
        pocket_report["override"] = {"declared": declared,
                                     "not_in_resolved_shell": sorted(set(declared) - set(resolved)),
                                     "resolved_but_unused": sorted(set(resolved) - set(declared))}
    else:
        design_positions = resolved
    st = prepare(tf, holo, dna, out_dir,
                 design_positions=design_positions,
                 effector_resname=meta["effector_resname"],
                 dbd_range=meta["dbd_range"],
                 expect_wt_11mer=meta.get("expect_wt_11mer"))

    paths = {k: v for k, v in st.items() if k != "qc"}
    # X_I_lig is the holo structure itself - the one state we have a crystal for.
    # X_D_lig has NO crystal by construction: a ligand sitting on the DNA-compatible backbone is
    # the strained state whose cost we are trying to measure. pose.py builds it, which is why
    # this dict is deliberately incomplete here and state_builder rejects a run without it.
    holo_chains = [c.id for c in classify_chains(load_assembly(holo))[0]][:2]
    cofactors = list(meta.get("required_cofactors") or ())
    paths["X_I_lig"] = write_state(holo, os.path.join(out_dir, "X_I_lig.pdb"),
                                   holo_chains, drop_het=True,
                                   keep_ligand=meta["effector_resname"],
                                   keep_cofactors=cofactors)
    # a declared cofactor that did not survive the write makes this state a different chemistry
    verify_cofactors(paths["X_I_lig"], cofactors, meta["effector_resname"])
    mapping = (st["qc"].get("induced") or {}).get("mapping") or {}
    return {"states": {"paths": paths,
                       "effector_resname": meta["effector_resname"],
                       "required_cofactors": cofactors,
                       "cofactor_restraints": meta.get("cofactor_restraints") or [],
                       "protected_native_trigger": [int(r) for r in
                                                    (meta.get("protected_native_trigger") or [])],
                       "golden_pair": meta.get("golden_pair") or {},
                       "dbd_range": meta["dbd_range"],
                       "chain": meta.get("chain", "A"),
                       "protein_chains": holo_chains,
                       "design_positions": design_positions,
                       "topology_mode": meta.get("topology_mode", "inducible_repressor"),
                       "entries": pick,
                       "qc": st["qc"]},
            "residue_mapping": mapping}
