"""Prepare and QC the native states for one scaffold. Upstream of everything else.

    X_D        DNA-compatible backbone (from the operator complex), no ligand
    X_I        induced backbone (from the effector complex), no ligand
    X_D_DNA    DNA-compatible backbone + operator
    X_I_DNA    induced backbone + operator      (built by superposition, see prepare())
    X_D_lig / X_I_lig   come from pose.py, which places the TARGET ligand

QC REJECTS; it does not warn. "Has a structure" is not "has a usable allosteric state":
  * is the bound heteroatom a real EFFECTOR or a crystallisation additive? A glycerol sitting in
    the pocket yields a confident, completely meaningless allosteric template.
  * is the DNA a real operator, or a short duplex / packing artefact?
  * is the oligomeric state right? TetR/LacI-family repressors work as DIMERS - with one chain the
    DBD-DBD geometry, i.e. the entire readout, is undefined.
  * does residue numbering match our reference? Constructs renumber silently.
  * are the design positions actually resolved, or are we inventing disordered density?

Worth checking rather than assuming: on TtgR, 2UXH/2UXO auth numbering happens to match UniProt
exactly (WT 11-mer HHAEMLLVNLH read from both), but that is luck, not a rule.
"""
import os
import csv
import json
import urllib.request
import numpy as np
from Bio.PDB import PDBParser, PDBIO, Select, Superimposer
from Bio.PDB.PDBExceptions import PDBConstructionWarning
import warnings
warnings.simplefilter("ignore", PDBConstructionWarning)

ADDITIVES = {"HOH", "SO4", "GOL", "EDO", "PO4", "CL", "NA", "K", "MG", "CA", "ZN", "MN", "ACT",
             "PEG", "PG4", "DMS", "TRS", "IOD", "BR", "NO3", "FMT", "EPE", "MPD", "BME", "CAC",
             "1PE", "P6G", "2PE", "PGE", "MRD", "IMD", "MES", "BEZ", "ACY", "EOH", "IPA",
             "UNL", "UNX", "HEZ", "HEX", "BU1", "DIO", "12P", "15P"}
DNA_RES = {"DA", "DT", "DG", "DC", "DU"}
MIN_OPERATOR_BP = 10


def fetch(pdb_id, out_dir):
    """ASYMMETRIC UNIT. Almost never what you want - see fetch_assembly()."""
    os.makedirs(out_dir, exist_ok=True)
    p = os.path.join(out_dir, "%s.pdb" % pdb_id.upper())
    if not os.path.exists(p):
        open(p, "wb").write(urllib.request.urlopen(
            "https://files.rcsb.org/download/%s.pdb" % pdb_id.upper(), timeout=60).read())
    return p


def fetch_assembly(pdb_id, out_dir, assembly=1):
    """BIOLOGICAL ASSEMBLY (.pdb1). This is what must be used, not the asymmetric unit.

    Verified the hard way on 1QPI (TetR-tetO, the ONLY TetR operator complex and therefore the
    foundation of the whole DNA-release criterion): its asymmetric unit contains ONE protein chain.
    The functional dimer is generated by crystallographic symmetry, so reading the ASU gives half a
    protein - and DBD-DBD geometry, hence Delta_d_DBD / Delta_theta_DBD / S_release, is undefined.
    Nothing would crash; we would simply compute confident nonsense from one DBD.

    The two representations differ per entry and both must be handled:
        1QPI  -> assembly is 2 MODEL blocks, symmetry copies, BOTH chains named 'A'
        1JT0  -> assembly is 1 MODEL block already containing chains A,B,C,D
    """
    os.makedirs(out_dir, exist_ok=True)
    p = os.path.join(out_dir, "%s_bio%d.pdb" % (pdb_id.upper(), assembly))
    if not os.path.exists(p):
        import gzip
        url = "https://files.rcsb.org/download/%s.pdb%d.gz" % (pdb_id.upper(), assembly)
        raw = gzip.decompress(urllib.request.urlopen(url, timeout=60).read())
        open(p, "wb").write(raw)
    return p


def _struct(pdb_path):
    return PDBParser(QUIET=True).get_structure("x", pdb_path)


def load_assembly(pdb_path):
    """-> a single Model with every symmetry copy merged and chains uniquely renamed.

    Multi-MODEL assemblies reuse chain IDs across copies, so a naive read collapses the dimer back
    to a monomer. Merging must happen before any chain counting or DBD geometry.
    """
    st = _struct(pdb_path)
    models = list(st)
    if len(models) == 1:
        return models[0]
    from Bio.PDB.Model import Model
    merged = Model(0)
    used = set()
    pool = [c for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"]
    for mi, m in enumerate(models):
        for ch in m:
            new_id = ch.id if (mi == 0 and ch.id not in used) else None
            if new_id is None:
                new_id = next((x for x in pool if x not in used), None)
                if new_id is None:
                    raise RuntimeError("ran out of chain IDs merging assembly")
            c = ch.copy()
            c.id = new_id
            c.detach_parent()
            merged.add(c)
            used.add(new_id)
    return merged


def classify_chains(model):
    prot, dna, het = [], [], []
    for ch in model:
        res = [r for r in ch if r.id[0] == " "]
        names = {r.get_resname().strip() for r in res}
        if res and names <= DNA_RES:
            dna.append(ch)
        elif len(res) > 30:
            prot.append(ch)
        for r in ch:
            if r.id[0] != " " and r.get_resname().strip() not in ADDITIVES:
                het.append((ch.id, r.get_resname().strip()))
    return prot, dna, het


def qc(pdb_path, expect_effector=None, expect_dimer=True, require_dna=False,
       design_positions=(), expect_wt_11mer=None):
    """-> (ok, report). Any problem is a rejection, not a warning."""
    rep = dict(pdb=os.path.basename(pdb_path), problems=[], notes=[])
    model = next(iter(_struct(pdb_path)))
    prot, dna, het = classify_chains(model)
    rep["n_protein_chains"] = len(prot)
    rep["n_dna_chains"] = len(dna)
    rep["heteroatoms"] = sorted({h[1] for h in het})

    if expect_dimer and len(prot) < 2:
        rep["problems"].append(
            "only %d protein chain(s): this family works as a dimer, so DBD-DBD geometry - the "
            "whole readout - is undefined" % len(prot))

    if expect_effector:
        if not any(h[1].upper() == expect_effector.upper() for h in het):
            rep["problems"].append("effector %s absent (heteroatoms present: %s)"
                                   % (expect_effector, rep["heteroatoms"] or "none"))

    if require_dna:
        if not dna:
            rep["problems"].append("no DNA chain: operator release cannot be measured")
        else:
            bp = min(len([r for r in c if r.id[0] == " "]) for c in dna)
            rep["operator_bp"] = bp
            if bp < MIN_OPERATOR_BP:
                rep["problems"].append("duplex only %d bp - too short for a real operator, likely "
                                       "crystal packing" % bp)

    if design_positions:
        if not prot:
            rep["problems"].append("no protein chain to map design positions onto")
        else:
            ch = max(prot, key=lambda c: sum(1 for r in c if r.id[0] == " "))
            have = {r.id[1]: r.get_resname() for r in ch if r.id[0] == " "}
            missing = [p for p in design_positions if p not in have]
            if missing:
                rep["problems"].append("design positions unresolved: %s" % missing)
            elif expect_wt_11mer:
                from .physallo.aa_filter import one
                got = "".join(one(have[p]) for p in design_positions)
                rep["wt_mer_in_pdb"] = got
                if got != expect_wt_11mer:
                    rep["problems"].append(
                        "numbering mismatch: PDB gives %s, reference is %s - this construct "
                        "renumbers, map it explicitly" % (got, expect_wt_11mer))
                else:
                    rep["notes"].append("numbering matches reference (%s)" % got)
    return (not rep["problems"]), rep


class _Keep(Select):
    def __init__(self, chains, drop_het=True, keep_resname=None):
        self.chains, self.drop_het, self.keep = set(chains), drop_het, keep_resname

    def accept_chain(self, c):
        return c.id in self.chains

    def accept_residue(self, r):
        if r.id[0] == " ":
            return True
        n = r.get_resname().strip()
        if n in ADDITIVES:
            return False
        if self.keep and n.upper() == self.keep.upper():
            return True
        return not self.drop_het


def write_state(pdb_path, out_path, chains, drop_het=True, keep_ligand=None):
    io = PDBIO()
    io.set_structure(_struct(pdb_path))
    io.save(out_path, _Keep(chains, drop_het, keep_ligand))
    return out_path


def _core_ca(chain, exclude_range):
    """CA atoms of the ligand-binding core, i.e. everything OUTSIDE the DBD."""
    lo, hi = exclude_range
    return {r.id[1]: r["CA"] for r in chain
            if r.id[0] == " " and "CA" in r and not (lo <= r.id[1] <= hi)}


def build_induced_on_dna(holo_pdb, dna_pdb, out_path, dbd_range, chain_i=None, chain_d=None):
    """X_I_DNA: put the INDUCED conformation onto the operator complex.

    Superpose on the ligand-binding CORE only, never on the DBD: the DBD is the readout. Fitting
    the DBD would force the induced conformation onto the operator and erase exactly the clash we
    are trying to measure.
    """
    mi, md = next(iter(_struct(holo_pdb))), next(iter(_struct(dna_pdb)))
    pi = [c for c in classify_chains(mi)[0]]
    pd = [c for c in classify_chains(md)[0]]
    ci = mi[chain_i] if chain_i else max(pi, key=lambda c: sum(1 for r in c if r.id[0] == " "))
    cd = md[chain_d] if chain_d else max(pd, key=lambda c: sum(1 for r in c if r.id[0] == " "))
    a, b = _core_ca(ci, dbd_range), _core_ca(cd, dbd_range)
    common = sorted(set(a) & set(b))
    if len(common) < 40:
        raise RuntimeError("only %d shared core CA - cannot superpose reliably" % len(common))
    sup = Superimposer()
    sup.set_atoms([b[i] for i in common], [a[i] for i in common])
    sup.apply([atom for r in ci for atom in r])
    io = PDBIO()
    io.set_structure(_struct(holo_pdb))
    io.save(out_path)
    return out_path, float(sup.rms), len(common)


def prepare(tf_name, holo_pdb, dna_pdb, out_dir, design_positions, effector_resname,
            dbd_range, expect_wt_11mer=None):
    """-> {'X_D','X_I','X_D_DNA','X_I_DNA','qc'}; raises if QC rejects the scaffold."""
    os.makedirs(out_dir, exist_ok=True)
    report = {}
    ok_i, report["induced"] = qc(holo_pdb, expect_effector=effector_resname,
                                 design_positions=design_positions,
                                 expect_wt_11mer=expect_wt_11mer)
    ok_d, report["dna_bound"] = qc(dna_pdb, require_dna=True,
                                   design_positions=design_positions,
                                   expect_wt_11mer=expect_wt_11mer)
    if not (ok_i and ok_d):
        raise RuntimeError("QC rejected %s:\n%s" % (tf_name, json.dumps(report, indent=2)))

    mi, md = next(iter(_struct(holo_pdb))), next(iter(_struct(dna_pdb)))
    ci = [c.id for c in classify_chains(mi)[0]][:2]
    pd_, dna_, _ = classify_chains(md)
    cd_prot = [c.id for c in pd_][:2]
    out = {
        "X_I": write_state(holo_pdb, os.path.join(out_dir, "X_I.pdb"), ci),
        "X_D": write_state(dna_pdb, os.path.join(out_dir, "X_D.pdb"), cd_prot),
        "X_D_DNA": write_state(dna_pdb, os.path.join(out_dir, "X_D_DNA.pdb"),
                               cd_prot + [c.id for c in dna_]),
    }
    p, rms, n = build_induced_on_dna(holo_pdb, dna_pdb, os.path.join(out_dir, "X_I_DNA.pdb"),
                                     dbd_range)
    out["X_I_DNA"] = p
    report["superposition"] = dict(core_rms=rms, n_core_ca=n, note="fit on ligand-binding core "
                                   "only; DBD excluded because it is the readout")
    out["qc"] = report
    json.dump(report, open(os.path.join(out_dir, "structure_qc.json"), "w"), indent=2)
    return out


def resolution(pdb_id):
    """RCSB resolution, or None. Used only to order candidates - never to reject silently."""
    try:
        import urllib.request
        j = json.load(urllib.request.urlopen(
            "https://data.rcsb.org/rest/v1/core/entry/%s" % pdb_id, timeout=30))
        r = (j.get("rcsb_entry_info") or {}).get("resolution_combined")
        return float(r[0]) if r else None
    except Exception:
        return None


def pick_entries(row):
    """Choose the holo and DNA entries to build the two backbones from.

    Refuses the PurR trap: tier is computed from counts, and a TF whose every effector-bound
    structure is a TERNARY complex has n_ternary>0 but holo_pdbs empty. Such a scaffold still has
    a usable X_D (the ternary backbone) but its X_I is the apo state and its topology is inverted -
    that is a corepressor, and it must be routed as one rather than silently built backwards.
    """
    holo = [x for x in (row.get("holo_pdbs") or "").split(";") if x]
    dna = [x for x in (row.get("dna_pdbs") or "").split(";") if x]
    n_tern = int(row.get("n_ternary") or 0)
    notes = []
    if not holo and n_tern > 0:
        raise RuntimeError(
            "%s has no effector-only structure: all %d effector-bound entries are ternary "
            "(TF+DNA+ligand). Its tier=%s was computed by counting ternary as both holo and DNA. "
            "This is a corepressor topology - X_I is the APO state, not a holo one - and it must "
            "be declared as topology_mode: corepressor before it can be built."
            % (row["tf_name"], n_tern, row.get("tier")))
    if not holo:
        raise RuntimeError("%s: no holo structure, cannot define the induced backbone"
                           % row["tf_name"])
    if not dna:
        raise RuntimeError(
            "%s: no operator complex, so X_D is undefined and S_release cannot be measured. "
            "This is a Tier-2 scaffold (%s). Building X_D from a homology model is a separate "
            "decision, not a default." % (row["tf_name"], row.get("tier_note", "")))
    def best(ids):
        scored = [(resolution(i), i) for i in ids]
        known = sorted([t for t in scored if t[0] is not None])
        if known:
            return known[0][1], known[0][0]
        notes.append("no resolution metadata for %s; took the first entry" % ",".join(ids))
        return ids[0], None
    h, hr = best(holo)
    d, dr = best(dna)
    return {"holo": h, "holo_res": hr, "dna": d, "dna_res": dr,
            "holo_pool": holo, "dna_pool": dna, "notes": notes}


def load_row(tf_name, db_path=None):
    db_path = db_path or os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                                      "data", "atf_structure_db.csv")
    with open(db_path) as f:
        for r in csv.DictReader(f):
            if r["tf_name"] == tf_name:
                return r
    raise KeyError("%s not in %s" % (tf_name, db_path))


def run(ctx):
    """requires ctx['scaffold']; produces ctx['states'], ctx['residue_mapping']"""
    sc = ctx["scaffold"]
    tf = sc["tf_name"] if isinstance(sc, dict) else sc
    row = load_row(tf, ctx.get("structure_db"))
    pick = pick_entries(row)

    out_dir = os.path.join(ctx["out_dir"], "states")
    holo = fetch_assembly(pick["holo"], out_dir)
    dna = fetch_assembly(pick["dna"], out_dir)

    st = prepare(tf, holo, dna, out_dir,
                 design_positions=sc.get("design_positions", ()),
                 effector_resname=sc["effector_resname"],
                 dbd_range=sc["dbd_range"],
                 expect_wt_11mer=sc.get("expect_wt_11mer"))

    paths = {k: v for k, v in st.items() if k != "qc"}
    # X_I_lig is the holo structure itself - the one state we have a crystal for.
    # X_D_lig has NO crystal by construction: a ligand sitting on the DNA-compatible backbone is
    # the strained state whose cost we are trying to measure. pose.py builds it, which is why
    # this dict is deliberately incomplete here and state_builder rejects a run without it.
    holo_chains = [c.id for c in classify_chains(next(iter(_struct(holo))))[0]][:2]
    paths["X_I_lig"] = write_state(holo, os.path.join(out_dir, "X_I_lig.pdb"),
                                   holo_chains, drop_het=True,
                                   keep_ligand=sc["effector_resname"])
    return {"states": {"paths": paths,
                       "effector_resname": sc["effector_resname"],
                       "dbd_range": sc["dbd_range"],
                       "chain": sc.get("chain", "A"),
                       "entries": pick,
                       "qc": st["qc"]},
            "residue_mapping": st["qc"].get("induced", {}).get("mapping")}
